### ISSUE TITLE
Error: Server Error The server encountered a temporary error and could not complete your request. Please try again in 30 seconds.

### ISSUE THREAD

**Issue by noman20** [fcat97/QuranApi#1]
https://jcenter.bintray.com/com/github/fcat97/QuranApi/0.4.37/QuranApi-0.4.37.pom
 I am getting this error what to do?

**Comment by fcat97** [comment]
API got an update. Please use the latest version.

Also make sure that you added the following line in your `project level` `build.gradle` file.

```
allprojects {
    repositories {
        // other repositories...
        maven { url "https://jitpack.io" }
    }
}
```
